language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements-test.txt

script:
  - pytest
  - if [ ${TRAVIS} ]; then  codecov -t "5010d5ed-ba43-488b-afd6-996d15f8ac43";  fi