site_name: Web Parser | Î²eta
site_url: https://github.com/invanalabs/web-parser
site_description: Web Parser lets you convert HTML, XML data into JSON using YAML configurations and occasionally with
  pythonic functions.
theme: yeti
extra_css: [extra-style.css]
repo_url: https://github.com/invanalabs/web-parser

nav:
- Home: index.md
- Tutorials:
  - HTML Extractor: tutorials/html-extractor.md
  - XML Extractor: tutorials/xml-extractor.md
- Manifest: manifest.md

