site_name: Web Parsers
site_url: https://github.com/invanalabs/web_parsers
site_description: Web Parsers lets you convert HTML, XML data into JSON using YAML configurations and occasionally with
  pythonic functions.
theme: yeti
extra_css: [extra-style.css]
repo_url: https://github.com/invanalabs/web_parsers

nav:
- Home: index.md
- Tutorials:
  - HTML Extractor: tutorials/html-extractor.md
  - XML Extractor: tutorials/xml-extractor.md
- Manifest: manifest.md

